
package com.lanou.service;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2018-01-22T20:03:20.515+08:00
 * Generated source version: 3.2.1
 * 
 */
public final class HelloService_HelloServiceImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://impl.service.lanou.com/", "HelloService");

    private HelloService_HelloServiceImplPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = HelloService_Service.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        HelloService_Service ss = new HelloService_Service(wsdlURL, SERVICE_NAME);
        HelloService port = ss.getHelloServiceImplPort();  
        
        {
        System.out.println("查询金额最大的信息...");
        com.lanou.service.Contracthisc _selectByMax__return = port.selectByMax();
        System.out.println("selectByMax.result=" + _selectByMax__return);


        }
        {
        System.out.println("查询所有的历史合同...");
        java.util.List<com.lanou.service.ContractBean> list = port.selectAll();
        for (ContractBean c : list) {
        	System.out.println("selectAll.result=" + c.getCONTRACTID());
		}
        
        


        }
        {
        System.out.println("根据合同id查询详细信息...");
        java.lang.String _selectByPrimaryKey_arg0 = "";
        com.lanou.service.Contracthisc _selectByPrimaryKey__return = port.selectByPrimaryKey("4028817a33812ffd013382048ff80024");
        System.out.println("selectByPrimaryKey.result=" + _selectByPrimaryKey__return.getCONTRACTID());


        }
        {
        System.out.println("查询前几个月的合同信息...");
        java.lang.String _selectByTime_arg0 = "3";
        java.util.List<com.lanou.service.Contracthisc> _selectByTime__return = port.selectByTime(_selectByTime_arg0);
        for (Contracthisc c : _selectByTime__return) {
            System.out.println("selectByTime.result=" + c.getCONTRACTID());

		}


        }
        {
        System.out.println("查询输入年份的合同信息..");
        java.lang.String _selectByYear_arg0 = "2017";
        java.util.List<com.lanou.service.Contracthisc> _selectByYear__return = port.selectByYear(_selectByYear_arg0);
        for (Contracthisc c : _selectByYear__return) {
            System.out.println("selectByYear.result=" + c.getCONTRACTID());

		}


        }
    
        {
        System.out.println("根据厂家,查询厂家下面的所有合同...");
        java.lang.String _selectByFactoryName_arg0 = "宏艺";
        java.util.List<com.lanou.service.Contracthisc> _selectByFactoryName__return = port.selectByFactoryName(_selectByFactoryName_arg0);
        for (Contracthisc c : _selectByFactoryName__return) {
            System.out.println("selectByFactoryName.result=" + c.getCONTRACTID());

		}


        }

        System.exit(0);
    }

}
