package com.lanou.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2018-01-22T20:03:20.570+08:00
 * Generated source version: 3.2.1
 * 
 */
@WebService(targetNamespace = "http://service.lanou.com/", name = "HelloService")
@XmlSeeAlso({ObjectFactory.class})
public interface HelloService {

    @WebMethod
    @RequestWrapper(localName = "selectByMax", targetNamespace = "http://service.lanou.com/", className = "com.lanou.service.SelectByMax")
    @ResponseWrapper(localName = "selectByMaxResponse", targetNamespace = "http://service.lanou.com/", className = "com.lanou.service.SelectByMaxResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.lanou.service.Contracthisc selectByMax();

    @WebMethod
    @RequestWrapper(localName = "selectAll", targetNamespace = "http://service.lanou.com/", className = "com.lanou.service.SelectAll")
    @ResponseWrapper(localName = "selectAllResponse", targetNamespace = "http://service.lanou.com/", className = "com.lanou.service.SelectAllResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<com.lanou.service.ContractBean> selectAll();

    @WebMethod
    @RequestWrapper(localName = "selectByPrimaryKey", targetNamespace = "http://service.lanou.com/", className = "com.lanou.service.SelectByPrimaryKey")
    @ResponseWrapper(localName = "selectByPrimaryKeyResponse", targetNamespace = "http://service.lanou.com/", className = "com.lanou.service.SelectByPrimaryKeyResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.lanou.service.Contracthisc selectByPrimaryKey(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebMethod
    @RequestWrapper(localName = "selectByTime", targetNamespace = "http://service.lanou.com/", className = "com.lanou.service.SelectByTime")
    @ResponseWrapper(localName = "selectByTimeResponse", targetNamespace = "http://service.lanou.com/", className = "com.lanou.service.SelectByTimeResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<com.lanou.service.Contracthisc> selectByTime(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebMethod
    @RequestWrapper(localName = "selectByYear", targetNamespace = "http://service.lanou.com/", className = "com.lanou.service.SelectByYear")
    @ResponseWrapper(localName = "selectByYearResponse", targetNamespace = "http://service.lanou.com/", className = "com.lanou.service.SelectByYearResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<com.lanou.service.Contracthisc> selectByYear(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebMethod
    @RequestWrapper(localName = "sayHi", targetNamespace = "http://service.lanou.com/", className = "com.lanou.service.SayHi")
    @ResponseWrapper(localName = "sayHiResponse", targetNamespace = "http://service.lanou.com/", className = "com.lanou.service.SayHiResponse")
    public void sayHi(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebMethod
    @RequestWrapper(localName = "selectByFactoryName", targetNamespace = "http://service.lanou.com/", className = "com.lanou.service.SelectByFactoryName")
    @ResponseWrapper(localName = "selectByFactoryNameResponse", targetNamespace = "http://service.lanou.com/", className = "com.lanou.service.SelectByFactoryNameResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<com.lanou.service.Contracthisc> selectByFactoryName(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
